include = [
  # "https://raw.githubusercontent.com/mrijken/check-config/refs/heads/main/example/checkers/http_check_config.toml",
  "http_check_config.toml",
  "folder/local_file.toml",
  "copy.toml",
  "unpack.toml",
]

[[file_absent]]
file = "output/to_be_removed"

[[file_present]]
file = "output/.bashrc"

[[file_present]]
file = "output/.gitconfig"
placeholder = """
[user]
        name = <your name>
        email = <your email>
"""

[[file_present]]
file = "output/.bashrc"
regex = "export KEY=.*"

[[lines_present]]
file = "output/.bashrc"
lines = "alias ll='ls -alF'"

[[lines_absent]]
file = "output/.bashrc"
lines = "alias to_be_removed='ls'"

[[key_absent]]
file = "output/test.json"
key.to_be_removed = {  }

[[key_absent]]
file = "output/test.toml"
key.to_be_removed = {  }

[[key_absent]]
file = "output/test.yaml"
key.to_be_removed = {  }

[[key_value_present]]
file = "output/test.json"
key.to_be_added = "value"

[[key_value_present]]
file = "output/test.toml"
key.to_be_added = "value"

[[key_value_present]]
file = "output/test.yaml"
key.to_be_added = "value"

[[key_value_present]]
file = "output/test.json"
key.to_be_kept.key = "value"
key.added.key = "1"

[[key_value_present]]
file = "output/test.toml"
key.to_be_kept.key = "value"
key.added.key = "value"

[[key_value_present]]
file = "output/test.yaml"
key.to_be_kept.key = "value"

[[entry_absent]]
file = "output/absent.json"
entry.list2 = ["already_absent"]

[[entry_absent]]
file = "output/absent.json"
entry.list = ["already_absent"]

[[entry_absent]]
file = "output/absent.json"
entry.list = ["to_be_removed", "already_absent"]

[[entry_absent]]
file = "output/absent.toml"
entry.list2 = ["already_absent"]

[[entry_absent]]
file = "output/absent.toml"
entry.list = ["already_absent"]

[[entry_absent]]
file = "output/test.toml"
entry.list = ["to_be_removed"]

[[entry_absent]]
file = "output/test.yaml"
entry.list2 = ["already_absent"]

[[entry_absent]]
file = "output/test.json"
entry.list = ["to_be_removed"]

[[entry_absent]]
file = "output/absent.yaml"
entry.list = ["already_absent"]

[[entry_absent]]
file = "output/test.yaml"
entry.list = ["to_be_removed"]

[[entry_present]]
file = "output/test.json"
entry.list2 = ["already_present"]

[[entry_present]]
file = "output/test.json"
entry.list = ["to_be_added", "to_be_kept"]

[[entry_present]]
file = "output/test.toml"
entry.list = ["to_be_added", "to_be_kept"]

[[entry_present]]
file = "output/test.toml"
entry.list2 = ["already_present"]

[[entry_present]]
file = "output/test.yaml"
entry.list = ["to_be_added", "to_be_kept"]

[[entry_present]]
file = "output/test.yaml"
tags = ["selected"]
entry.list2 = ["already_present"]

[[entry_present]]
file = "output/test.yaml"
tags = ["not_selected"]
entry.list3 = ["not added"]

[[git_fetched]]
dir = "output/check-config"
repo = "https://github.com/mrijken/check-config.git"
branch = "main"
