[__config__]
include = [
        "https://raw.githubusercontent.com/mrijken/check-config/refs/heads/main/example/checkers/http_check_config.toml",
        "folder/local_file.toml"
]

["output/to_be_removed".file_absent]

["output/.bashrc".file_present]

["output/.gitconfig".file_present]
__placeholder__ = """
[user]
        name = <your name>
        email = <your email>
"""

["output/.bashrc".file_regex_match]
__regex__ = "export KEY=.*"

["output/.bashrc".lines_present]
__lines__ = "alias ll='ls -alF'"

["output/.bashrc".lines_absent]
__lines__ = "alias to_be_removed='ls'"

["output/test.json".key_absent.to_be_removed]

["output/test.toml".key_absent.to_be_removed]

["output/test.yaml".key_absent.to_be_removed]

["output/test.json".key_value_present]
to_be_added = "value"

["output/test.toml".key_value_present]
to_be_added = "value"

["output/test.yaml".key_value_present]
to_be_added = "value"

["output/test.json".key_value_present.to_be_kept]
key = "value"

["output/test.toml".key_value_present.to_be_kept]
key = "value"

["output/test.yaml".key_value_present.to_be_kept]
key = "value"

["output/test.json".entry_absent.list2]
__items__ = ["already_absent"]

["output/absent.json".entry_absent.list]
__items__ = ["already_absent"]

["output/test.json".entry_absent.list]
__items__ = ["to_be_removed", "already_absent"]

["output/test.toml".entry_absent.list2]
__items__ = ["already_absent"]

["output/absent.toml".entry_absent.list]
__items__ = ["already_absent"]

["output/test.toml".entry_absent.list]
__items__ = ["to_be_removed"]

["output/test.yaml".entry_absent.list2]
__items__ = ["already_absent"]

["output/absent.yaml".entry_absent.list]
__items__ = ["already_absent"]

["output/test.yaml".entry_absent.list]
__items__ = ["to_be_removed"]

["output/test.json".entry_present.list2]
__items__ = ["already_present"]

["output/test.json".entry_present.list]
__items__ = ["to_be_added", "to_be_kept"]

["output/test.toml".entry_present.list]
__items__ = ["to_be_added", "to_be_kept"]

["output/test.toml".entry_present.list2]
__items__ = ["already_present"]

["output/test.yaml".entry_present.list]
__items__ = ["to_be_added", "to_be_kept"]

["output/test.yaml".entry_present.list2]
__items__ = ["already_present"]

